### ISSUE TITLE
Add Lar_Hmm sound sample as pickup sound

### ISSUE THREAD

**Issue by Castigavi** [Dermahn/Project-Fix-Lara-v2#1]
Peter Connelly released original TR4 sound samples. In the package there are three Lar_Hmm sounds that would be perfect as a new sound when Lara picks up stuff.

https://www.tomb-of-ash.com/original-sfx-and-voice-over-from-tomb-raider-4-5-and-6/

**Comment by Dermahn** [comment]
This is outside the scope of this project. Level builders may choose to add this sound effect themselves.
